# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 * * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: marlowl
          template: classic
          base: activity
          base_indepth: yes
          base_skip: yes
          config_timezone: Europe/Amsterdam
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          plugin_repositories: yes
          plugin_repositories_featured: marlowl/vue-voting-dapp, Consensys/quorum-kubernetes, marlowl/postgres-gcs-backup
          plugin_repositories_order: featured, pinned, starred, random
          plugin_repositories_starred: 0
